FROM python:3.10.16-slim-bullseye AS python-java

RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-11-jdk-headless \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"



FROM python-java AS builder

WORKDIR /server

COPY pyproject.toml requirements.txt ./
RUN pip wheel --no-cache-dir --no-deps --wheel-dir wheels -r requirements.txt

COPY app app

RUN pip wheel --no-cache-dir --no-deps --wheel-dir wheels .

FROM python-java AS runner

WORKDIR /server

COPY --from=builder /server/wheels /wheels

RUN pip install --no-cache-dir /wheels/* && rm  -rf wheels

COPY --from=builder /server/app /server/app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]