FROM python-java

WORKDIR /server

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

RUN pip install tabula-py[jpype]

COPY app app


EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]