FROM python-java AS builder

WORKDIR /server

COPY pyproject.toml requirements.txt ./
RUN pip wheel --no-cache-dir --no-deps --wheel-dir wheels -r requirements.txt

COPY app app

RUN pip wheel --no-cache-dir --no-deps --wheel-dir wheels .

FROM python-java AS runner

WORKDIR /server

COPY --from=builder /server/wheels /wheels

RUN pip install --no-cache-dir /wheels/* && rm  -rf wheels

COPY --from=builder /server/app /server/app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]